#!/bin/bash
location="schurtransform/version.txt"
version=$(cat "$location")
prefix=$(echo "$version" | grep -oP '^([\d]+\.[\d]+\.)')
microversion=$(echo "$version" | grep -oP '([\d]+)$')
microversion=$(( microversion + 1 ))
echo "$prefix$microversion" > $location
