#!/bin/bash
versionline=$(cat setup.py | grep -oP "^version = '[0-9]+\.[0-9]+\.[0-9]+'$")
macroversion=$(echo $versionline | grep -oP "^version = '[0-9]+\.[0-9]+\.")
microversion=$(echo $versionline | grep -oP "[0-9]+'")
microversion=$(echo $microversion | grep -oP "[0-9]+")
microversion=$(( microversion + 1 ))
newversionline="$macroversion$microversion'"

echo $versionline
echo $macroversion
echo $microversion
echo $newversionline
echo 's/$versionline/$newversionline/g'
sed -i "s/$versionline/$newversionline/g" setup.py

releaseline=$(cat docs/conf.py | grep -oP "^release = '[0-9]+\.[0-9]+\.[0-9]+'$")
macroversion=$(echo $releaseline | grep -oP "^release = '[0-9]+\.[0-9]+\.")
microversion=$(echo $releaseline | grep -oP "[0-9]+'")
microversion=$(echo $microversion | grep -oP "[0-9]+")
microversion=$(( microversion + 1 ))
newreleaseline="$macroversion$microversion'"
echo $releaseline
echo $macroversion
echo $microversion
echo $newreleaseline
sed -i "s/$releaseline/$newreleaseline/g" docs/conf.py
